id: A9FEA24E7
title: Remainder Torma Offering for Seven-Line Prayer Guru Yoga
type: translation
pechas:
- IF341724C
- ICB9B48F8
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:50:16.758459
  last_modified_at: 2023-01-04 11:50:16.758469
  collections:
  - Dudjom Rinpoche Series
  - Works of Tibetan Masters
alignment_to_base:
  IF341724C/CE33: '1789'
  ICB9B48F8/A0C8: '1789'
